# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc13cf909d6c29af94ce0f198e9fa5cd62d078b07419548d0729364ac885ac632551e9de3e1d43f063618e9593e1148dce34232867cd687d6894f9c89362a7d7

test:
  secret_key_base: 27978e5ecd3804f3dc702c02639d0fa1947048fadc5d84d594e5f4b1f423af59092a08b9cc0ab2d9bf0b3343f1ed516d333c7739219b51ca7d90fcd975c7a9b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
